   name: Deploy my Lambda Function

   on:
        push: 
            branches:
                -main
   jobs:
        build:
            run-on: ubuntu-latest
            steps:
               -name: Check out the code
               uses: actions/checkout@v2
                -name: Set up python
                 uses: actions/setup-python@v2
                with:
                    python-version 3.8
                -name: install libraries
                 run: |
                      cd function
                      python -m install --update pip
                      if [ -f requirements.txt ]; then pip install -r requirements.txt -t . ; 
                -name create zip bundle:
                 run: |
                      cd function
                      zip -r ../${{ github.sha}}.zip .
                -name Archieve artifact
                 uses: actions/upload artifact@v2
                 with:
                    name: zipped-bundle
                    path: ${{ github.sha }}.zip

                    
